= StellarisポートレートMOD作成用テンプレート
:author: Xen-Shuto
:toc: left
:toc-title: 目次

== 0.注意事項
　2025/8/1現在、コピー用スクリプトに不具合を確認しています。 +
　申し訳ございませんが、自力での編集をお願いいたします。 +
　中身は https://github.com/Xen-Shuto/species_portrait_template[species_portrait_template] と同じです。 +

== 1.このMODについて
　これはStellarisのポートレートMOD作成用の雛型です。 +
　画像や用意したが、面倒なファイルの編集を極力したくない方向けの超絶簡易版です。 +

== 2.利用規約（ライセンス）
本テンプレートを利用・参照する際は、必ず link:LICENSE[LICENSE] ファイルをご確認ください。 +
本テンプレートは非公式のファンコンテンツであり、作者（Xen-Shuto）や公式（Paradox Interactive）を騙る行為、および本テンプレート自体の商用利用・改変再配布を禁止しています。 +
本テンプレートを用いて制作されたMOD（作品）についても、本規約に基づき非商用での利用に限られます。 +

== 2.できること
* 静止画ポートレートMODの作成 +

== 3.できないこと
* 上記以外 +
アニメーションポートレートMODの作成 +
名称リストとの連動 +
その他、起源やイベントの追加など +

== 4.必要なもの
* テキストエディタ +
notepad（メモ帳）ではダメ！ +
文字コード指定の出来るテキストエディタが必要 +
編集するファイルはテキストだが、全てUTF-8 BOM無し（ローカライズのみBOM有り）なので +
と思っていたが、メモ帳でも ANSI(SJIS)、UTF-8 BOM有り/無しの保存ができる模様 +
* ポートレート用の画像 +
最低でも１枚は用意すること +
※画像生成AIで作成した画像をサンプル画像として添付しています。 +
* 画像編集ソフト +
DDS(DirectDraw surface)形式とPSD（Photoshopドキュメント）形式が取り扱えて、背景が透過できる物 +
この２形式が取り扱えるなら、背景の透過はできるはず） +
作者はPaint.netを使用した +

== 5.使い方
* CODEからDownload ZIPで丸ごとDownloadしてください。 +
* readme.txt(readme.adocではない)のの記述に従ってください。 +

== 6.更新履歴
[cols="1,1,10" grid=all options="autowidth"]
|===
| 更新日付   | Var.     | 更新内容

| 2025/07/28 | 0.00.005 | 名称リストに対応
| 2025/06/08 | 0.00.004 | portrait_setsのspecies_classを修正
| 2025/06/07 | 0.00.003 | 対応バージョンをv4.x.xに修正
| 2025/02/16 | 0.00.002 | 都市外観名称、艦船外観名称等に悪影響があったため、内部のディレクトリ名、ファイル名を変更。
| 2024/08/16 | 0.00.001 | 新規作成
|===

== 7.その他
* 作者の環境では雛型のままでポートレートを追加してプレイできることは確認済みなので、 +
追加できないぞと言われても困る
* 画像は自分で用意してください。 +

== 8.謝辞
　MOD作成ガイドのコメント欄で反応下さった方々、おかげで公開する踏ん切りがつきました。 +
　特に参考情報としてご自身が管理されているGitHubを教えて下さったのFatalErrorJP様、 +
　大変参考になりました。また、コードの添削ありがとうございました。 +
　ローカライズ定義のコメントを使わせて頂いてます。 +

